### ISSUE TITLE
Bitget Futures unable to fetch list of symobols

### ISSUE THREAD

**Issue by delsin474** [msei99/pbgui#58]
Backtest page does not load and when we click on Update symbols button we get following error:

2024-06-10 12:15:37.287 Uncaught app exception
Traceback (most recent call last):
  File "/home/delsin/pgbuienv/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/home/delsin/pbgui/pages/3_Backtest.py", line 219, in <module>
    bt_add()
  File "/home/delsin/pbgui/pages/3_Backtest.py", line 25, in bt_add
    my_bt.edit_base()
  File "/home/delsin/pbgui/Base.py", line 101, in edit_base
    self.user = st.session_state.base_user
  File "/home/delsin/pbgui/Base.py", line 53, in user
    self._symbol = self._symbols[0]
IndexError: list index out of range

<img width="953" alt="image" src="https://github.com/msei99/pbgui/assets/31121668/9ad50853-6820-4b9e-99c2-345ebf35c320">

**Comment by msei99** [comment]
what ccxt version are you using? If you are on the latest passivbot version with ccxt version 4.3.24 then there was a change in ccxt that make pbgui not working. At the moment it is only fixed in the "ent" branch, but I don't recommend using this branach for running live bots, as it is not fully tested. But if it's for backtesting, you can try it.

**Comment by msei99** [comment]
Fixed in latest version in dev branch
